### ISSUE TITLE
Text im Kurschabschnitt anzeigen

### ISSUE THREAD

**Issue by julialeede** [sudile/moodle-mod_feedbackbox#1]
Wenn das Kreuz bei Beschreibung im Kurs anzeigen angeklickt ist, wird dieser nicht im Kursabschnitt angezeigt. 

![Beschreibung](https://user-images.githubusercontent.com/103051042/162411091-6d284ad3-3f95-4c7c-a738-b744cdf83726.PNG)

**Comment by cli-ish** [comment]
Ist behoben.
