### ISSUE TITLE
Benachrichtigung bei einer Feedback Box in einem alten Kurs deaktivieren

### ISSUE THREAD

**Issue by julialeede** [sudile/moodle-mod_feedbackbox#2]
Problem: Wenn die Feedback Box durch die Kopie eines Kurses vervielfältigt wird, erhalten Teilnehmende des neuen Kurses Erinnerungen zur Abgabe des Feedbacks. Das Feedback lässt sich dann nicht deaktivieren mit den Einstellungen.
Lösung 1: Bei dem konkreten Problemfall kann der/die Admin in dem Kurs den Wert notifystudents von 1 auf 0 setzen
Lösung 2: In Moodle selbst kann der/die Admin generell die Kopie einer Feedback Box bei der Kopie eines Kurses deaktivieren.

**Comment by cli-ish** [comment]
Ist behoben.
